version: "3.6"
services:
  db:
    image: postgres:15
    container_name: tkt2019_ryhma_chat-db
    environment:
      POSTGRES_PASSWORD: password
      PGPORT: 6543
    volumes:
      - pg-data:/var/lib/postgresql/data/
      - ./provision_db.sql:/docker-entrypoint-initdb.d/1_provision_db.sql
    restart: unless-stopped
    command: ["postgres", "-p", "6543", "-c", "log_statement=all"]
    ports:
      - "6543:6543"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 20
volumes:
  pg-data:
