CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE groups (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX groups_created_by_idx ON groups (created_by);

CREATE TABLE messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    sender_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    group_id BIGINT NOT NULL REFERENCES groups ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX messages_group_id_idx ON messages (group_id);
CREATE INDEX messages_sender_id_idx ON messages (sender_id);
CREATE INDEX messages_created_at_idx ON messages (created_at);

CREATE TABLE group_invites (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT NOT NULL REFERENCES groups ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE users_groups (
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    group_id BIGINT NOT NULL REFERENCES groups ON DELETE CASCADE ,
    PRIMARY KEY (user_id, group_id)
);

ALTER TABLE users_groups OWNER TO marvin;
ALTER TABLE users OWNER TO marvin;
ALTER TABLE messages OWNER TO marvin;
ALTER TABLE groups OWNER TO marvin;
ALTER TABLE group_invites OWNER TO marvin;
